src/cn/itcast/store/product/domain/Cart.java
package cn.itcast.store.product.domain;

import java.io.Serializable;
import java.util.LinkedHashMap;

public class Cart implements Serializable{
	//总金额必须有初始值
	private double totalPrice = 0.0;
	//使用linkedHashMap存储购物项信息，便于删除操作，且是有序的
	private LinkedHashMap<String, CartItem> map = new LinkedHashMap<>();
	public double getTotalPrice() {
		return totalPrice;
	}
	public void setTotalPrice(double totalPrice) {
		this.totalPrice = totalPrice;
	}
	public LinkedHashMap<String, CartItem> getMap() {
		return map;
	}
	public void setMap(LinkedHashMap<String, CartItem> map) {
		this.map = map;
	}
	public Cart() {
		// TODO Auto-generated constructor stub
	}
	/**
	 * 添加购物车里的购物项，如果有则累加，没有则添加
	 * @param ci
	 * @param product 
	 */
	public void addCartItem(CartItem ci, Product product) {
		// TODO Auto-generated method stub
		String pid = ci.getProduct().getPid();
		CartItem old = map.get(pid);
		if(old == null){
			map.put(pid, ci);
		}else{
//			old.setProduct(product);
			old.setCount(old.getCount() + ci.getCount());
		}
		totalPrice += ci.getSubtotal();
	}
	
	/**\
	 * 删除购物项
	 * @param cart
	 * @param pid
	 */
	public void delCartItem(Cart cart, String pid) {
		// TODO Auto-generated method stub
		totalPrice -= cart.map.get(pid).getSubtotal();
		cart.map.remove(pid);
	}
	
	/**
	 * 清空购物车
	 */
	public void clearCart() {
		// TODO Auto-generated method stub
		map.clear();
		totalPrice = 0.0;
	}
}

src/cn/itcast/store/utils/PageBean.java
package cn.itcast.store.utils;

import java.io.Serializable;
import java.util.List;

public class PageBean<T> implements Serializable {

    // 1.起始索引(计算)
    private int startIndex;

    // 2.每页显示记录数(指定写死)
    private int pageSize;

    // 3.当前页面(用户要查看的页码)（前台获取）
    private int pageNumber;

    // 4.总记录数(查询得到)
    private int totalRecord;

    // 5.总页码(计算)
    private int totalPage;

    // 6.存放查询出来所有商品信息的结果对象
    private List<T> result;

    public int getStartIndex() {
        return (this.getPageNumber() - 1) * this.getPageSize();
    }

    public void setStartIndex(int startIndex) {
        this.startIndex = startIndex;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    public int getPageNumber() {
        return pageNumber;
    }

    public void setPageNumber(int pageNumber) {
        this.pageNumber = pageNumber;
    }

    public int getTotalRecord() {
        return totalRecord;
    }

    public void setTotalRecord(int totalRecord) {
        this.totalRecord = totalRecord;
    }

    public int getTotalPage() {
        return this.getTotalRecord() % this.getPageSize() == 0 ? (this.getTotalRecord() / this.getPageSize())
                : (this.getTotalRecord() / this.getPageSize() + 1);
    }

    public void setTotalPage(int totalPage) {
        this.totalPage = totalPage;
    }

    public List<T> getResult() {
        return result;
    }

    public void setResult(List<T> result) {
        this.result = result;
    }

    public PageBean() {

    }
    
    //为使用EL表达式
    public int getResultSize(){
    	if(result == null){
    		return 0;
    	}
    	return result.size();
    }
}

WebContent/NewFile.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<script src="${pageContext.request.contextPath}/js/jquery-1.11.3.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/layer/layer.js" type="text/javascript"></script>
<title>Insert title here</title>
</head>
<body>

</body>
</html>

WebContent/cart.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!doctype html>
<html>

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>购物车</title>
		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/bootstrap.min.css" type="text/css" />
		<script src="${pageContext.request.contextPath}/js/jquery-1.11.3.min.js" type="text/javascript"></script>
		<script src="${pageContext.request.contextPath}/js/bootstrap.min.js" type="text/javascript"></script>
		<!-- 引入自定义css文件 style.css -->
		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" type="text/css" />
		<style>
			body {
				margin-top: 20px;
				margin: 0 auto;
			}
			
			.carousel-inner .item img {
				width: 100%;
				height: 300px;
			}
			
			.container .row div {
				/* position:relative;
	 float:left; */
			}
			
			font {
				color: #3164af;
				font-size: 18px;
				font-weight: normal;
				padding: 0 10px;
			}
		</style>
	</head>

	<body>

		
			<!--
            	描述：菜单栏
            	
            -->
			<!--
            	描述：导航条
            -->
            <!-- 
            	因为菜单栏和导航条在任何页面都有使用，
            	
            	所以为了方便统一维护，增强代码的扩展性
            	
            	我们将其抽取成为一个单独的JSP页面--header.jsp
            	
            	然后静态导入进来即可
             -->
			<%@include file="header.jsp" %>


		<div class="container">
			<div class="row">

				<div style="margin:0 auto; margin-top:10px;width:950px;">
					<strong style="font-size:16px;margin:5px 0;">购物车详情  </strong><span>${msg }</span>
					<table class="table table-bordered">
						<tbody>
							<tr class="warning">
								<th>图片</th>
								<th>商品</th>
								<th>价格</th>
								<th>数量</th>
								<th>小计</th>
								<th>操作</th>
							</tr>
							<c:if test="${not empty cart && not empty cart.map }">
								<c:forEach items="${cart.map }" var="entry" >
									<tr class="active">
										<td width="60" width="40%">
											<input type="hidden" name="id" value="22">
											<img src="${pageContext.request.contextPath}/${entry.value.product.pimage}" width="70" height="60">
										</td>
										<td width="30%">
											<a target="_blank">${entry.value.product.pname }</a>
										</td>
										<td width="20%">
											￥${entry.value.product.shop_price }
										</td>
										<td width="10%">
											${entry.value.count }
										</td>
										<td width="15%">
											<span class="subtotal">￥${entry.value.subtotal }</span>
										</td>
										<td>
											<a href="${pageContext.request.contextPath }/ProductServlet?method=delCart&pid=${entry.value.product.pid}">
												<input type="button" value="删除" class="btn btn-danger" />
											</a>
										</td>
									</tr>
								</c:forEach>
							</c:if>
						</tbody>
					</table>
				</div>
			</div>

			<div style="margin-right:130px;">
				<div style="text-align:right;">
					<em style="color:#ff6600;">
				登录后确认是否享有优惠&nbsp;&nbsp;
			</em> 赠送积分: <em style="color:#ff6600;"> ${cart.totalPrice /1000} </em>&nbsp; 商品金额: <strong style="color:#ff6600;">￥${cart.totalPrice }</strong>
				</div>
				<div style="text-align:right;margin-top:10px;margin-bottom:10px;">
					<a href="${pageContext.request.contextPath}/ProductServlet?method=clearCart" id="clear" class="clear">清空购物车</a>
					<a href="${pageContext.request.contextPath}/OrderServlet?method=makeOrderList">
						<input type="submit" width="100" value="提交订单" name="submit" border="0" style="background: url('${pageContext.request.contextPath}/images/register.gif') no-repeat scroll 0 0 rgba(0, 0, 0, 0);
						height:35px;width:100px;color:white;">
					</a>
				</div>
			</div>

		</div>

		<div style="margin-top:50px;">
			<img src="${pageContext.request.contextPath}/image/footer.jpg" width="100%" height="78" alt="我们的优势" title="我们的优势" />
		</div>

		<div style="text-align: center;margin-top: 5px;">
			<ul class="list-inline">
				<li><a>关于我们</a></li>
				<li><a>联系我们</a></li>
				<li><a>招贤纳士</a></li>
				<li><a>法律声明</a></li>
				<li><a>友情链接</a></li>
				<li><a target="_blank">支付方式</a></li>
				<li><a target="_blank">配送方式</a></li>
				<li><a>服务声明</a></li>
				<li><a>广告声明</a></li>
			</ul>
		</div>
		<div style="text-align: center;margin-top: 5px;margin-bottom:20px;">
			Copyright &copy; 2005-2016 传智商城 版权所有
		</div>

	</body>

</html>

WebContent/header.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<script type="text/javascript">
	$(function (){
		$.post("${pageContext.request.contextPath}/ProductServlet",{method:"findAllCategoryByRedis"},function (data){
			$(data).each(function (){
				//alert(this['cname']);
				var li = "<li class='active'><a href='${pageContext.request.contextPath}/ProductServlet?method=findProductByCategory&pageNumber=1&cid="+this['cid']+"'>"+this['cname']+"</a></li>";
				$("#category").append(li);
			})			
		},"json");
	});
</script>
<!--
         	描述：菜单栏
         -->
<div class="container-fluid">
	<div class="col-md-4">
		<img src="img/logo2.png" />
	</div>
	<div class="col-md-5">
		<img src="${pageContext.request.contextPath}/img/header.png" />
	</div>
	<div class="col-md-3" style="padding-top:20px">
		<ol class="list-inline">
		<c:choose>
			<c:when test="${not empty existUser }">
				<li><a href="${pageContext.request.contextPath}/index.jsp">欢迎你,${existUser.username }</a></li>
				<li><a href="${pageContext.request.contextPath}/cart.jsp">购物车</a></li>
				<li><a href="${pageContext.request.contextPath}/OrderServlet?method=findAllOrders&pageNumber=1">我的订单</a></li>
				<li><a href="${pageContext.request.contextPath}/UserServlet?method=logout">退出</a></li>
			</c:when>
			<c:otherwise>
				<li><a href="${pageContext.request.contextPath}/login.jsp">登录</a></li>
				<li><a href="${pageContext.request.contextPath}/register.jsp">注册</a></li>
			</c:otherwise>
		</c:choose>
		</ol>
	</div>
</div>
<!--
         	描述：导航条
         -->
<div class="container-fluid">
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="${pageContext.request.contextPath }/index.jsp">首页</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav" id="category">
					
				</ul>
				<form class="navbar-form navbar-right" role="search">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>

			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container-fluid -->
	</nav>
</div>

WebContent/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>商城主页</title>
		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/bootstrap.min.css" type="text/css" />
		<script src="${pageContext.request.contextPath}/js/jquery-1.11.3.min.js" type="text/javascript"></script>
		<script src="${pageContext.request.contextPath}/js/bootstrap.min.js" type="text/javascript"></script>
		<script type="text/javascript">
			$(function (){
				/*异步方式显示热门商品和最新商品信息*/
			$.post("${pageContext.request.contextPath}/ProductServlet",{method:"findProductHot"},function (data){
				$(data).each(function (){
					var temp = '<div class="col-md-2" style="text-align:center;height:200px;padding:10px 0px;">';
					temp+='<a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByPid&pid='+this["pid"]+'">';
					temp+='<img src="'+this["pimage"]+'" width="130" height="130" style="display: inline-block;">';
					temp+='</a>';
					temp+='<p><a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByPid&pid='+this["pid"]+'" style="color:#666">'+this["pname"]+'</a></p>';
					temp+='<p><font color="#E4393C" style="font-size:16px">&yen;'+this["shop_price"]+'</font></p>';
					$("#product_info").append(temp);
				});
			},"json");
			$.post("${pageContext.request.contextPath}/ProductServlet",{method:"findProductNew"},function (data){
				$(data).each(function (){
					var temp = '<div class="col-md-2" style="text-align:center;height:200px;padding:10px 0px;">';
					temp += '<a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByPid&pid='+this["pid"]+'">';
					temp += '<img src="'+this["pimage"]+'"width="130" height="130" style="display: inline-block;">';
					temp += '</a>';
					temp += '<p><a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByPid&pid='+this["pid"]+'" style="color:#666">'+this["pname"]+'</a></p>';
					temp += '<p><font color="#E4393C" style="font-size:16px">&yen;'+this["shop_price"]+'</font></p>';
					$("#product_info_new").append(temp);
				})
			},"json");
				/*同步方式显示热门商品和最新商品信息*/
			/* 	if($("#is_hot div").size()==1 || $("#new div").size()==1){
					location.href="${pageContext.request.contextPath}/ProductServlet?method=findProductNewAndHot";
				} */
			});
		</script>
	</head>

	<body>
		<div class="container-fluid">

			<!--
            	描述：菜单栏
            	
            -->
			<!--
            	描述：导航条
            -->
            <!-- 
            	因为菜单栏和导航条在任何页面都有使用，
            	
            	所以为了方便统一维护，增强代码的扩展性
            	
            	我们将其抽取成为一个单独的JSP页面--header.jsp
            	
            	然后静态导入进来即可
             -->
			<%@include file="header.jsp" %>

			<!--
            	描述：轮播条
            -->
			<div class="container-fluid">
				<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
					<!-- Indicators -->
					<ol class="carousel-indicators">
						<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
						<li data-target="#carousel-example-generic" data-slide-to="1"></li>
						<li data-target="#carousel-example-generic" data-slide-to="2"></li>
					</ol>

					<!-- Wrapper for slides -->
					<div class="carousel-inner" role="listbox">
						<div class="item active">
							<img src="${pageContext.request.contextPath}/img/1.jpg">
							<div class="carousel-caption">

							</div>
						</div>
						<div class="item">
							<img src="${pageContext.request.contextPath}/img/2.jpg">
							<div class="carousel-caption">

							</div>
						</div>
						<div class="item">
							<img src="${pageContext.request.contextPath}/img/3.jpg">
							<div class="carousel-caption">

							</div>
						</div>
					</div>

					<!-- Controls -->
					<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			</div>
			<!--
            	描述：商品显示
            -->
			<div class="container-fluid">
				<div class="col-md-12">
					<h2>热门商品&nbsp;&nbsp;<img src="img/title2.jpg"/></h2>
				</div>
				<div class="col-md-2" style="border:1px solid #E7E7E7;border-right:0;padding:0;">
					<img src="${pageContext.request.contextPath}/products/hao/big01.jpg" width="205" height="404" style="display: inline-block;"/>
				</div>
				<div class="col-md-10" id="is_hot">
					<div class="col-md-6" style="text-align:center;height:200px;padding:0px;">
						<a href="product_info.htm">
							<img src="${pageContext.request.contextPath}/products/hao/middle01.jpg" width="516px" height="200px" style="display: inline-block;">
						</a>
					</div>
					
					<!--异步显示热门商品信息div  -->
					<div id="product_info"></div>
					<!--同步显示热门商品信息  -->
					<%-- <c:if test="${not empty hot }">
						<c:forEach items="${hot }" var="product">
							<div class="col-md-2" style="text-align:center;height:200px;padding:0px;">
								<a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByPid&pid=${product.pid }">
									<img src="${pageContext.request.contextPath}/${product.pimage}" width="130" height="130" style="display: inline-block;">
								</a>
								<p><a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByPid&pid=${product.pid }" style='color:#666'>${product.pname }</a></p>
								<p><font color="#E4393C" style="font-size:16px">&yen;${product.shop_price }</font></p>
							</div>
						</c:forEach>
					</c:if> --%>
				</div>
			</div>
			<!--
            	描述：广告部分
            -->
            <div class="container-fluid">
				<img src="${pageContext.request.contextPath}/products/hao/ad.jpg" width="100%"/>
			</div>
			<!--
            	作者：ci2713@163.com
            	时间：2015-12-30
            	描述：商品显示
            -->
			<div class="container-fluid">
				<div class="col-md-12">
					<h2>最新商品&nbsp;&nbsp;<img src="img/title2.jpg"/></h2>
				</div>
				<div class="col-md-2" style="border:1px solid #E7E7E7;border-right:0;padding:0;">
					<img src="${pageContext.request.contextPath}/products/hao/big01.jpg" width="205" height="404" style="display: inline-block;"/>
				</div>
				
				
				
				
				<div class="col-md-10" id="new">
					<div class="col-md-6" style="text-align:center;height:200px;padding:0px;">
						<a href="product_info.htm">
							<img src="${pageContext.request.contextPath}/products/hao/middle01.jpg" width="516px" height="200px" style="display: inline-block;">
						</a>
					</div>
					
					<!--异步显示最新商品信息div  -->
					<div id="product_info_new"></div>
					<!--同步显示最新商品信息  -->
					<%-- <c:if test="${not empty newproducts }">
						<c:forEach items="${newproducts }" var="product">
							<div class="col-md-2" style="text-align:center;height:200px;padding:0px;">
								<a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByPid&pid=${product.pid }">
									<img src="${pageContext.request.contextPath}/${product.pimage}" width="130" height="130" style="display: inline-block;">
								</a>
								<p><a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByPid&pid=${product.pid }" style='color:#666'>${product.pname }</a></p>
								<p><font color="#E4393C" style="font-size:16px">&yen;${product.shop_price }</font></p>
							</div>
						</c:forEach>
					</c:if> --%>
				</div>
			</div>			
			<!--
            	描述：页脚部分
            -->
			<div class="container-fluid">
				<div style="margin-top:50px;">
					<img src="${pageContext.request.contextPath}/img/footer.jpg" width="100%" height="78" alt="我们的优势" title="我们的优势" />
				</div>
		
				<div style="text-align: center;margin-top: 5px;">
					<ul class="list-inline">
						<li><a href="info.html">关于我们</a></li>
						<li><a>联系我们</a></li>
						<li><a>招贤纳士</a></li>
						<li><a>法律声明</a></li>
						<li><a>友情链接</a></li>
						<li><a>支付方式</a></li>
						<li><a>配送方式</a></li>
						<li><a>服务声明</a></li>
						<li><a>广告声明</a></li>
					</ul>
				</div>
				<div style="text-align: center;margin-top: 5px;margin-bottom:20px;">
					Copyright &copy; 2005-2016 黑马商城 版权所有
				</div>
			</div>
		</div>
	</body>

</html>

WebContent/product_list.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!doctype html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>商品列表页面</title>
		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/bootstrap.min.css" type="text/css" />
		<script src="${pageContext.request.contextPath}/js/jquery-1.11.3.min.js" type="text/javascript"></script>
		<script src="${pageContext.request.contextPath}/js/bootstrap.min.js" type="text/javascript"></script>
		<!-- 引入自定义css文件 style.css -->
		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" type="text/css" />

		<style>
			body {
				margin-top: 20px;
				margin: 0 auto;
				width: 100%;
			}
			.carousel-inner .item img {
				width: 100%;
				height: 300px;
			}
		</style>
	</head>

	<body>
		
			<!--
            	描述：菜单栏
            	
            -->
			<!--
            	描述：导航条
            -->
            <!-- 
            	因为菜单栏和导航条在任何页面都有使用，
            	
            	所以为了方便统一维护，增强代码的扩展性
            	
            	我们将其抽取成为一个单独的JSP页面--header.jsp
            	
            	然后静态导入进来即可
             -->
			<%@include file="header.jsp" %>

		
		<div class="row" style="width:1210px;margin:0 auto;">
			<div class="col-md-12">
				<ol class="breadcrumb">
					<li><a href="#">首页</a></li>
				</ol>
			</div>
			<div class="row" >
				<c:if test="${not empty pageBean && not empty pageBean.result }">
					<c:forEach items="${pageBean.result }" varStatus="vs" var="product">
						<c:if test="${vs.count==1 || vs.count == 7}">
							<div class="row" >
						</c:if>
						
						<div class="col-md-2">
							<a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByPid&pid=${product.pid }">
								<img src="${pageContext.request.contextPath}/${product.pimage}" width="170" height="170" style="display: inline-block;">
							</a>
							<p><a href="product_info.html" style='color:green'>${product.pname }</a></p>
							<p><font color="#FF0000">商城价:￥${product.shop_price}</font></p>
						</div>
						
						<c:if test="${vs.count==6 || vs.count == 12 || vs.count == pageBean.resultSize}">
							</div>
						</c:if>
					</c:forEach>
				</c:if>
			</div>
		</div>

		<!--分页 -->
		<div style="width:380px;margin:0 auto;margin-top:50px;">
			<ul class="pagination" style="text-align:center; margin-top:10px;">
				<!-- 上一页 -->
				<c:if test="${not empty pageBean}">
					<c:choose>
						<c:when test="${pageBean.pageNumber == 1}">
							<li class="disabled">
								<a href="javaScript:void(0)" aria-label="Previous">
									<span aria-hidden="true">&laquo;</span>
								</a>
							</li>
						</c:when>
						<c:otherwise>
							<li class="">
								<a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByCategory&pageNumber=${pageBean.pageNumber-1 }&cid=${param.cid}" aria-label="Previous">
									<span aria-hidden="true">&laquo;</span>
								</a>
							</li>
						</c:otherwise>
					</c:choose>
				<!-- 当前页 -->
					<c:forEach begin="1" end="${pageBean.totalPage }" var="vs">
						<c:choose>
							<c:when test="${pageBean.pageNumber == vs }">
								<li class="disabled"><a href="javaScript:void(0)">${vs }</a></li>
							</c:when>
							<c:otherwise>
								<li class=""><a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByCategory&pageNumber=${vs}&cid=${param.cid}">${vs }</a></li>
							</c:otherwise>
						</c:choose>
					</c:forEach>
				<!-- 下一页 -->
					<c:choose>
						<c:when test="${pageBean.pageNumber == pageBean.totalPage}">
							<li class="disabled">
								<a href="javaScript:void(0)" aria-label="">
									<span aria-hidden="true">&raquo;</span>
								</a>
							</li>
						</c:when>
						<c:otherwise>
							<li class="">
								<a href="${pageContext.request.contextPath }/ProductServlet?method=findProductByCategory&pageNumber=${pageBean.pageNumber+1 }&cid=${param.cid}" aria-label="Previous">
									<span aria-hidden="true">&raquo;</span>
								</a>
							</li>
						</c:otherwise>
					</c:choose>
				</c:if>
			</ul>
		</div>
		<!-- 分页结束=======================        -->

		<!--
       		商品浏览记录:
        -->
		<div style="width:1210px;margin:0 auto; padding: 0 9px;border: 1px solid #ddd;border-top: 2px solid #999;height: 246px;">

			<h4 style="width: 50%;float: left;font: 14px/30px;">浏览记录</h4>
			<div style="width: 50%;float: right;text-align: right;"><a href="">more</a></div>
			<div style="clear: both;"></div>

			<div style="overflow: hidden;">

				<ul style="list-style: none;">
					<li style="width: 150px;height: 216;float: left;margin: 0 8px 0 0;padding: 0 18px 15px;text-align: center;"><img src="${pageContext.request.contextPath}/products/1/cs10001.jpg" width="130px" height="130px" /></li>
				</ul>

			</div>
		</div>
		<div style="margin-top:50px;">
			<img src="${pageContext.request.contextPath}/image/footer.jpg" width="100%" height="78" alt="我们的优势" title="我们的优势" />
		</div>

		<div style="text-align: center;margin-top: 5px;">
			<ul class="list-inline">
				<li><a>关于我们</a></li>
				<li><a>联系我们</a></li>
				<li><a>招贤纳士</a></li>
				<li><a>法律声明</a></li>
				<li><a>友情链接</a></li>
				<li><a target="_blank">支付方式</a></li>
				<li><a target="_blank">配送方式</a></li>
				<li><a>服务声明</a></li>
				<li><a>广告声明</a></li>
			</ul>
		</div>
		<div style="text-align: center;margin-top: 5px;margin-bottom:20px;">
			Copyright &copy; 2005-2016 传智商城 版权所有
		</div>

	</body>

</html>